# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Load settings from vagrant.yml or vagrant.yml.dist
current_dir = File.dirname(File.expand_path(__FILE__))
if File.file?("#{current_dir}/vagrant.yml")
    config_file = YAML.load_file("#{current_dir}/vagrant.yml")
end

Vagrant.configure("2") do |config|
  machine = config_file['machine']
  proxy = config_file['proxy']
  
  proxy_enabled = ENV['PROXY_ENABLE'] == 'true' || proxy['enabled'] == true
  puts "Vagrant für " + machine['hostname'] 


  if proxy_enabled
  
    puts "PROXY is ENABLED"
    # nutze vagrant-procyconf für entsprechende Einträge in /etc/environment und /etc/profile.d/proxy.sh
    # zu finden mit: sudo grep -nri _proxy= /etc
    
    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http     = proxy['http']
      config.proxy.https    = proxy['https']
      config.proxy.no_proxy = proxy['noproxy']
    end
  end

  # https://app.vagrantup.com/centos/boxes/7
  config.vm.box = "centos/7"
  config.vm.box_version = "1902.01"

  # Network
  config.vm.hostname = machine['hostname']
  config.vm.network "private_network", ip: machine['ip']
    
  # Copy SSH Keys
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/id_rsa"    , destination: "/home/vagrant/ssh/id_rsa"

  config.vm.provision :shell, path: "provision-tools.sh"
  config.vm.provision :shell, path: "provision-user.sh"
  config.vm.provision :shell, path: "provision-docker.sh"
  config.vm.provision :shell, path: "provision-samba.sh"
  for projects in config_file['projects'] do
	name=nil
	repository=nil
    for p in projects do
	  if p[0]=='name'
	    name=p[1]
	  end
	  if p[0]=='repository'
	    repository=p[1]
	  end
	  if name!=nil && repository!=nil
        config.vm.provision :shell, path: "provision-project.sh", args: [ name, repository ]
	  end
	end
  end

  config.vm.provision :shell, path: "provision-dns-docker.sh", args: [ machine['hostname'], machine['ip'], machine['host-ip'], machine['domain'] ]
  config.vm.provision :shell, path: "provision-nosecurity.sh"
  config.vm.provision :shell, path: "provision-permissions.sh"
  

  config.vm.provider "virtualbox" do |v|
    v.name = "ad-docker-ws"
    v.memory = machine['memory']
    v.cpus = machine['cpus']
  end


end

