version: '3.2'
networks:
  wordpress:
    ipam:
      driver: default 
services:
  wordpress:
    image: wordpress:5.2.1
    restart: "unless-stopped"
    networks:
      - wordpress
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
  mysql:
    image: mysql:5.7
    restart: "unless-stopped"
    networks:
      - wordpress    
    environment:
      MYSQL_ROOT_PASSWORD: example   

